import { NextRequest } from 'next/server';
import crypto from 'crypto';
import prisma from '@/lib/prisma';
import { apiResponse, apiError, serializeUser } from '@/lib/api-middleware';
import { generateToken, hashToken } from '@/lib/auth';

/**
 * POST /api/auth/auto-login
 *
 * Exchanges a one-time auto-login token for OAuth access + refresh tokens.
 * Used by the iOS app after email verification to skip the manual login step.
 *
 * The auto-login token is generated by the verify-email API when platform=ios,
 * passed to the app via deep link (fotolokashen://email-verified?token=xxx),
 * and is valid for 5 minutes / single use.
 *
 * Request body:
 * - token: The one-time auto-login token
 * - client_id: OAuth client identifier
 * - device_name: (optional) Device description
 * - ip_address: (optional) Client IP
 * - user_agent: (optional) Client user agent
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { token, client_id, device_name, ip_address, user_agent } = body;

    if (!token || !client_id) {
      return apiError('Missing required parameters', 400, 'INVALID_REQUEST');
    }

    // Validate client exists
    const client = await prisma.oAuthClient.findUnique({
      where: { clientId: client_id },
    });

    if (!client) {
      return apiError('Invalid client_id', 400, 'INVALID_CLIENT');
    }

    // Find user with this auto-login token (hash incoming token to match stored hash)
    const user = await prisma.user.findFirst({
      where: {
        autoLoginToken: hashToken(token),
        emailVerified: true,
        isActive: true,
      },
    });

    if (!user) {
      console.log('❌ Auto-login failed: Invalid token');
      return apiError('Invalid or expired auto-login token', 400, 'INVALID_TOKEN');
    }

    // Check expiry
    if (user.autoLoginTokenExpiry && user.autoLoginTokenExpiry < new Date()) {
      // Clear the expired token
      await prisma.user.update({
        where: { id: user.id },
        data: { autoLoginToken: null, autoLoginTokenExpiry: null },
      });
      console.log('❌ Auto-login failed: Token expired');
      return apiError('Auto-login token has expired. Please log in manually.', 400, 'TOKEN_EXPIRED');
    }

    // Clear the token immediately (single-use)
    await prisma.user.update({
      where: { id: user.id },
      data: {
        autoLoginToken: null,
        autoLoginTokenExpiry: null,
        lastLoginAt: new Date(),
      },
    });

    // Generate access token (JWT)
    const serialized = serializeUser(user);
    const accessToken = generateToken(serialized, false);

    // Create session
    const sessionExpiresAt = new Date();
    sessionExpiresAt.setDate(sessionExpiresAt.getDate() + 1); // 24 hours

    const reqIp = ip_address ||
      request.headers.get('x-forwarded-for') ||
      request.headers.get('x-real-ip') ||
      'unknown';
    const reqUA = user_agent ||
      request.headers.get('user-agent') ||
      'fotolokashen-ios';

    // Clean up existing iOS sessions
    await prisma.session.deleteMany({
      where: {
        userId: user.id,
        deviceType: {
          in: ['ios', 'mobile-browser-ios'],
        },
      },
    });

    await prisma.session.create({
      data: {
        token: accessToken,
        userId: user.id,
        expiresAt: sessionExpiresAt,
        deviceType: 'ios',
        ipAddress: reqIp,
        userAgent: reqUA,
        deviceName: device_name || null,
        loginMethod: 'auto_login_email_verified',
        isActive: true,
      },
    });

    // Generate refresh token
    const refreshToken = crypto.randomBytes(32).toString('base64url');
    const refreshExpiresAt = new Date();
    refreshExpiresAt.setDate(refreshExpiresAt.getDate() + 30); // 30 days

    await prisma.oAuthRefreshToken.create({
      data: {
        token: refreshToken,
        clientId: client.clientId,
        userId: user.id,
        scopes: ['read', 'write'],
        expiresAt: refreshExpiresAt,
        deviceType: 'ios',
      },
    });

    if (process.env.NODE_ENV !== 'production') {
      console.log('✅ Auto-login successful after email verification');
      console.log(`   User ID: ${user.id}`);
    }

    return apiResponse({
      access_token: accessToken,
      refresh_token: refreshToken,
      token_type: 'Bearer',
      expires_in: 86400,
      scope: 'read write',
      user: {
        id: user.id,
        email: user.email,
        username: user.username,
        avatar: user.avatar,
      },
    });
  } catch (error) {
    console.error('❌ Auto-login error:', error);
    return apiError('Auto-login failed', 500, 'SERVER_ERROR');
  }
}
